#!/bin/sh
set -eu

NQ_HOST="${NQ_HOST:-192.168.86.38}"
NQ_USER="${NQ_USER:-root}"
SSH_OPTS="${SSH_OPTS:--o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=10}"
NQ_MCBSP_LEGACY_ELEMENT="${NQ_MCBSP_LEGACY_ELEMENT:-1}"
NQ_SDMA_PERIOD_BYTES="${NQ_SDMA_PERIOD_BYTES:-4128}"
NQ_SDMA_PERIODS="${NQ_SDMA_PERIODS:-4}"
NQ_MCBSP_LEGACY_THRESHOLD_FRAME="${NQ_MCBSP_LEGACY_THRESHOLD_FRAME:-1}"
NQ_MCBSP_LEGACY_PM_RUNTIME_HOLD="${NQ_MCBSP_LEGACY_PM_RUNTIME_HOLD:-0}"
NQ_MCBSP_NO_RX_ERR_IRQ="${NQ_MCBSP_NO_RX_ERR_IRQ:-1}"
NQ_MCBSP_LEGACY_TX_IRQ="${NQ_MCBSP_LEGACY_TX_IRQ:-1}"
NQ_MCBSP_NO_XRST_RESET="${NQ_MCBSP_NO_XRST_RESET:-0}"
NQ_MCBSP_FORCE_XRST_RESET_US="${NQ_MCBSP_FORCE_XRST_RESET_US:-0}"
NQ_MCBSP_STOP_ON_TX_UNDERFLOW="${NQ_MCBSP_STOP_ON_TX_UNDERFLOW:-0}"
NQ_MCBSP_TX_BURST="${NQ_MCBSP_TX_BURST:-0}"
NQ_MCBSP_BUFFER_SIZE_OVERRIDE="${NQ_MCBSP_BUFFER_SIZE_OVERRIDE:-0}"
NQ_MCBSP_TRIGGER_THRESHOLD="${NQ_MCBSP_TRIGGER_THRESHOLD:-0}"
NQ_MCBSP_PIO_TONE_MS="${NQ_MCBSP_PIO_TONE_MS:-0}"
NQ_MCBSP_PIO_TONE_FREQ="${NQ_MCBSP_PIO_TONE_FREQ:-440}"
NQ_MCBSP_PIO_TONE_AMP="${NQ_MCBSP_PIO_TONE_AMP:-4096}"
NQ_MCBSP_PIO_THRESHOLD="${NQ_MCBSP_PIO_THRESHOLD:-64}"
NQ_MCBSP_PIO_TIMER_US="${NQ_MCBSP_PIO_TIMER_US:-125}"
NQ_MCBSP_PIO_FILL_WORDS="${NQ_MCBSP_PIO_FILL_WORDS:-32}"
NQ_MCBSP_PIO_IRQ="${NQ_MCBSP_PIO_IRQ:-0}"
NQ_MCBSP_PIO_XRDY_POLL="${NQ_MCBSP_PIO_XRDY_POLL:-0}"
NQ_MCBSP_PIO_DETACHED_STOP="${NQ_MCBSP_PIO_DETACHED_STOP:-0}"
NQ_MCBSP_FIFO_POLL_MS="${NQ_MCBSP_FIFO_POLL_MS:-0}"
NQ_MCBSP_FIFO_TRACE_SAMPLES="${NQ_MCBSP_FIFO_TRACE_SAMPLES:-0}"
NQ_MCBSP_DLB_TRACE_FRAMES="${NQ_MCBSP_DLB_TRACE_FRAMES:-0}"
NQ_MCBSP_DLB_BLOCK_FRAMES="${NQ_MCBSP_DLB_BLOCK_FRAMES:-480}"
NQ_MCBSP_DLB_DUMP_BLOCKS="${NQ_MCBSP_DLB_DUMP_BLOCKS:-64}"
NQ_MCBSP_RCR2_OVERRIDE="${NQ_MCBSP_RCR2_OVERRIDE:--1}"
NQ_MCBSP_XCR2_OVERRIDE="${NQ_MCBSP_XCR2_OVERRIDE:--1}"
NQ_MCBSP_SRGR1_OVERRIDE="${NQ_MCBSP_SRGR1_OVERRIDE:--1}"
NQ_MCBSP_SRGR2_OVERRIDE="${NQ_MCBSP_SRGR2_OVERRIDE:--1}"
NQ_MCBSP_PCR0_OVERRIDE="${NQ_MCBSP_PCR0_OVERRIDE:--1}"
NQ_MCBSP_XCCR_OVERRIDE="${NQ_MCBSP_XCCR_OVERRIDE:--1}"
NQ_MCBSP_DUMP_REGS="${NQ_MCBSP_DUMP_REGS:-0}"
NQ_TAS571X_DUMP_REGS="${NQ_TAS571X_DUMP_REGS:-1}"
NQ_TAS571X_LEGACY_STREAM_REINIT="${NQ_TAS571X_LEGACY_STREAM_REINIT:-1}"
NQ_TAS571X_LEGACY_POWER_DOWN="${NQ_TAS571X_LEGACY_POWER_DOWN:-0}"
NQ_TAS571X_MUTE_ON_TRIGGER="${NQ_TAS571X_MUTE_ON_TRIGGER:--1}"
NQ_TAS571X_IGNORE_MUTE="${NQ_TAS571X_IGNORE_MUTE:-0}"
NQ_TAS571X_SDI_OVERRIDE="${NQ_TAS571X_SDI_OVERRIDE:--1}"
NQ_TAS571X_SYS_CTRL1_OVERRIDE="${NQ_TAS571X_SYS_CTRL1_OVERRIDE:--1}"
NQ_TAS571X_SKIP_HW_PARAMS="${NQ_TAS571X_SKIP_HW_PARAMS:-0}"
NQ_TAS571X_CYCLE_MCLK_ON_LEGACY_RESET="${NQ_TAS571X_CYCLE_MCLK_ON_LEGACY_RESET:-0}"
NQ_TAS571X_ASYNC_LEGACY_STREAM_REINIT_MS="${NQ_TAS571X_ASYNC_LEGACY_STREAM_REINIT_MS:--1}"
NQ_TAS571X_ERR_POLL_MS="${NQ_TAS571X_ERR_POLL_MS:-0}"
NQ_TAS571X_FLAT_DSP="${NQ_TAS571X_FLAT_DSP:-0}"
NQ_STEELHEAD_AUDIO_DUMP="${NQ_STEELHEAD_AUDIO_DUMP:-1}"
NQ_AUDIO_FORMAT="${NQ_AUDIO_FORMAT:-i2s}"
NQ_AUDIO_INVERSION="${NQ_AUDIO_INVERSION:-nb-nf}"
NQ_LEGACY_S16_ONLY="${NQ_LEGACY_S16_ONLY:-1}"
NQ_STEELHEAD_CODEC_POWER_FIRST="${NQ_STEELHEAD_CODEC_POWER_FIRST:-0}"
NQ_STEELHEAD_CODEC_MCLK_STARTUP="${NQ_STEELHEAD_CODEC_MCLK_STARTUP:-0}"
NQ_STEELHEAD_MCBSP_CLK_STARTUP="${NQ_STEELHEAD_MCBSP_CLK_STARTUP:-0}"
NQ_STEELHEAD_MCBSP_CLK_HW_PARAMS="${NQ_STEELHEAD_MCBSP_CLK_HW_PARAMS:-0}"
NQ_STEELHEAD_SKIP_CODEC_FMT="${NQ_STEELHEAD_SKIP_CODEC_FMT:-0}"
NQ_STEELHEAD_LINK_FMT="${NQ_STEELHEAD_LINK_FMT:-1}"
NQ_STEELHEAD_LDC="${NQ_STEELHEAD_LDC:-0}"
NQ_BCLK_FS="${NQ_BCLK_FS:-0}"
NQ_RELOAD_DMA="${NQ_RELOAD_DMA:-0}"
NQ_DMA_LEGACY_CYCLIC_SYNC="${NQ_DMA_LEGACY_CYCLIC_SYNC:-1}"
NQ_DMA_LEGACY_CYCLIC_BURST="${NQ_DMA_LEGACY_CYCLIC_BURST:-1}"
NQ_DMA_LEGACY_CYCLIC_PACK="${NQ_DMA_LEGACY_CYCLIC_PACK:-1}"
NQ_DMA_LEGACY_CYCLIC_BLOCK_IRQ="${NQ_DMA_LEGACY_CYCLIC_BLOCK_IRQ:-1}"
NQ_DMA_DUMP_CYCLIC="${NQ_DMA_DUMP_CYCLIC:-1}"
NQ_DMA_DUMP_IRQ_LIMIT="${NQ_DMA_DUMP_IRQ_LIMIT:-24}"
NQ_DMA_CYCLIC_BURST_BITS="${NQ_DMA_CYCLIC_BURST_BITS:--1}"
NQ_DMA_FORCE_DESCRIPTOR_RESIDUE="${NQ_DMA_FORCE_DESCRIPTOR_RESIDUE:-0}"
NQ_DMA_AUDIO_TONE="${NQ_DMA_AUDIO_TONE:-0}"
NQ_DMA_AUDIO_TONE_RATE="${NQ_DMA_AUDIO_TONE_RATE:-48000}"
NQ_DMA_AUDIO_TONE_FREQ="${NQ_DMA_AUDIO_TONE_FREQ:-440}"
NQ_DMA_AUDIO_TONE_AMP="${NQ_DMA_AUDIO_TONE_AMP:-2048}"
NQ_DMA_AUDIO_TONE_CHANNEL="${NQ_DMA_AUDIO_TONE_CHANNEL:-0}"
NQ_DMA_AUDIO_TONE_DEV_ADDR="${NQ_DMA_AUDIO_TONE_DEV_ADDR:-0x49024008}"
NQ_DMA_AUDIO_TONE_NO_IRQ="${NQ_DMA_AUDIO_TONE_NO_IRQ:-0}"
NQ_DMA_AUDIO_TONE_FAKE_PERIOD="${NQ_DMA_AUDIO_TONE_FAKE_PERIOD:-0}"
NQ_DMA_FORCE_LCH_SIG="${NQ_DMA_FORCE_LCH_SIG:-0}"
NQ_DMA_FORCE_LCH="${NQ_DMA_FORCE_LCH:--1}"
NQ_DMA_FORCE_RW_PRIORITY="${NQ_DMA_FORCE_RW_PRIORITY:-0}"

ssh $SSH_OPTS "$NQ_USER@$NQ_HOST" \
	"NQ_SDMA_PERIOD_BYTES=$NQ_SDMA_PERIOD_BYTES NQ_SDMA_PERIODS=$NQ_SDMA_PERIODS NQ_MCBSP_LEGACY_ELEMENT=$NQ_MCBSP_LEGACY_ELEMENT NQ_MCBSP_LEGACY_THRESHOLD_FRAME=$NQ_MCBSP_LEGACY_THRESHOLD_FRAME NQ_MCBSP_LEGACY_PM_RUNTIME_HOLD=$NQ_MCBSP_LEGACY_PM_RUNTIME_HOLD NQ_MCBSP_NO_RX_ERR_IRQ=$NQ_MCBSP_NO_RX_ERR_IRQ NQ_MCBSP_LEGACY_TX_IRQ=$NQ_MCBSP_LEGACY_TX_IRQ NQ_MCBSP_NO_XRST_RESET=$NQ_MCBSP_NO_XRST_RESET NQ_MCBSP_FORCE_XRST_RESET_US=$NQ_MCBSP_FORCE_XRST_RESET_US NQ_MCBSP_STOP_ON_TX_UNDERFLOW=$NQ_MCBSP_STOP_ON_TX_UNDERFLOW NQ_MCBSP_TX_BURST=$NQ_MCBSP_TX_BURST NQ_MCBSP_BUFFER_SIZE_OVERRIDE=$NQ_MCBSP_BUFFER_SIZE_OVERRIDE NQ_MCBSP_TRIGGER_THRESHOLD=$NQ_MCBSP_TRIGGER_THRESHOLD NQ_MCBSP_PIO_TONE_MS=$NQ_MCBSP_PIO_TONE_MS NQ_MCBSP_PIO_TONE_FREQ=$NQ_MCBSP_PIO_TONE_FREQ NQ_MCBSP_PIO_TONE_AMP=$NQ_MCBSP_PIO_TONE_AMP NQ_MCBSP_PIO_THRESHOLD=$NQ_MCBSP_PIO_THRESHOLD NQ_MCBSP_PIO_TIMER_US=$NQ_MCBSP_PIO_TIMER_US NQ_MCBSP_PIO_FILL_WORDS=$NQ_MCBSP_PIO_FILL_WORDS NQ_MCBSP_PIO_IRQ=$NQ_MCBSP_PIO_IRQ NQ_MCBSP_PIO_XRDY_POLL=$NQ_MCBSP_PIO_XRDY_POLL NQ_MCBSP_PIO_DETACHED_STOP=$NQ_MCBSP_PIO_DETACHED_STOP NQ_MCBSP_FIFO_POLL_MS=$NQ_MCBSP_FIFO_POLL_MS NQ_MCBSP_FIFO_TRACE_SAMPLES=$NQ_MCBSP_FIFO_TRACE_SAMPLES NQ_MCBSP_DLB_TRACE_FRAMES=$NQ_MCBSP_DLB_TRACE_FRAMES NQ_MCBSP_DLB_BLOCK_FRAMES=$NQ_MCBSP_DLB_BLOCK_FRAMES NQ_MCBSP_DLB_DUMP_BLOCKS=$NQ_MCBSP_DLB_DUMP_BLOCKS NQ_MCBSP_RCR2_OVERRIDE=$NQ_MCBSP_RCR2_OVERRIDE NQ_MCBSP_XCR2_OVERRIDE=$NQ_MCBSP_XCR2_OVERRIDE NQ_MCBSP_SRGR1_OVERRIDE=$NQ_MCBSP_SRGR1_OVERRIDE NQ_MCBSP_SRGR2_OVERRIDE=$NQ_MCBSP_SRGR2_OVERRIDE NQ_MCBSP_PCR0_OVERRIDE=$NQ_MCBSP_PCR0_OVERRIDE NQ_MCBSP_XCCR_OVERRIDE=$NQ_MCBSP_XCCR_OVERRIDE NQ_MCBSP_DUMP_REGS=$NQ_MCBSP_DUMP_REGS NQ_TAS571X_DUMP_REGS=$NQ_TAS571X_DUMP_REGS NQ_TAS571X_LEGACY_STREAM_REINIT=$NQ_TAS571X_LEGACY_STREAM_REINIT NQ_TAS571X_MUTE_ON_TRIGGER=$NQ_TAS571X_MUTE_ON_TRIGGER NQ_TAS571X_IGNORE_MUTE=$NQ_TAS571X_IGNORE_MUTE NQ_TAS571X_SDI_OVERRIDE=$NQ_TAS571X_SDI_OVERRIDE NQ_TAS571X_SYS_CTRL1_OVERRIDE=$NQ_TAS571X_SYS_CTRL1_OVERRIDE NQ_TAS571X_SKIP_HW_PARAMS=$NQ_TAS571X_SKIP_HW_PARAMS NQ_TAS571X_CYCLE_MCLK_ON_LEGACY_RESET=$NQ_TAS571X_CYCLE_MCLK_ON_LEGACY_RESET NQ_TAS571X_ASYNC_LEGACY_STREAM_REINIT_MS=$NQ_TAS571X_ASYNC_LEGACY_STREAM_REINIT_MS NQ_TAS571X_ERR_POLL_MS=$NQ_TAS571X_ERR_POLL_MS NQ_TAS571X_FLAT_DSP=$NQ_TAS571X_FLAT_DSP NQ_STEELHEAD_AUDIO_DUMP=$NQ_STEELHEAD_AUDIO_DUMP NQ_AUDIO_FORMAT=$NQ_AUDIO_FORMAT NQ_AUDIO_INVERSION=$NQ_AUDIO_INVERSION NQ_LEGACY_S16_ONLY=$NQ_LEGACY_S16_ONLY NQ_STEELHEAD_CODEC_POWER_FIRST=$NQ_STEELHEAD_CODEC_POWER_FIRST NQ_STEELHEAD_CODEC_MCLK_STARTUP=$NQ_STEELHEAD_CODEC_MCLK_STARTUP NQ_STEELHEAD_MCBSP_CLK_STARTUP=$NQ_STEELHEAD_MCBSP_CLK_STARTUP NQ_STEELHEAD_MCBSP_CLK_HW_PARAMS=$NQ_STEELHEAD_MCBSP_CLK_HW_PARAMS NQ_STEELHEAD_SKIP_CODEC_FMT=$NQ_STEELHEAD_SKIP_CODEC_FMT NQ_STEELHEAD_LINK_FMT=$NQ_STEELHEAD_LINK_FMT NQ_STEELHEAD_LDC=$NQ_STEELHEAD_LDC NQ_BCLK_FS=$NQ_BCLK_FS NQ_RELOAD_DMA=$NQ_RELOAD_DMA NQ_DMA_LEGACY_CYCLIC_SYNC=$NQ_DMA_LEGACY_CYCLIC_SYNC NQ_DMA_LEGACY_CYCLIC_BURST=$NQ_DMA_LEGACY_CYCLIC_BURST NQ_DMA_LEGACY_CYCLIC_PACK=$NQ_DMA_LEGACY_CYCLIC_PACK NQ_DMA_LEGACY_CYCLIC_BLOCK_IRQ=$NQ_DMA_LEGACY_CYCLIC_BLOCK_IRQ NQ_DMA_DUMP_CYCLIC=$NQ_DMA_DUMP_CYCLIC NQ_DMA_DUMP_IRQ_LIMIT=$NQ_DMA_DUMP_IRQ_LIMIT NQ_DMA_CYCLIC_BURST_BITS=$NQ_DMA_CYCLIC_BURST_BITS NQ_DMA_FORCE_DESCRIPTOR_RESIDUE=$NQ_DMA_FORCE_DESCRIPTOR_RESIDUE NQ_DMA_AUDIO_TONE=$NQ_DMA_AUDIO_TONE NQ_DMA_AUDIO_TONE_RATE=$NQ_DMA_AUDIO_TONE_RATE NQ_DMA_AUDIO_TONE_FREQ=$NQ_DMA_AUDIO_TONE_FREQ NQ_DMA_AUDIO_TONE_AMP=$NQ_DMA_AUDIO_TONE_AMP NQ_DMA_AUDIO_TONE_CHANNEL=$NQ_DMA_AUDIO_TONE_CHANNEL NQ_DMA_AUDIO_TONE_DEV_ADDR=$NQ_DMA_AUDIO_TONE_DEV_ADDR NQ_DMA_AUDIO_TONE_NO_IRQ=$NQ_DMA_AUDIO_TONE_NO_IRQ NQ_DMA_AUDIO_TONE_FAKE_PERIOD=$NQ_DMA_AUDIO_TONE_FAKE_PERIOD NQ_DMA_FORCE_LCH_SIG=$NQ_DMA_FORCE_LCH_SIG NQ_DMA_FORCE_LCH=$NQ_DMA_FORCE_LCH NQ_DMA_FORCE_RW_PRIORITY=$NQ_DMA_FORCE_RW_PRIORITY sh -s" <<'REMOTE'
	"NQ_SDMA_PERIOD_BYTES=$NQ_SDMA_PERIOD_BYTES NQ_SDMA_PERIODS=$NQ_SDMA_PERIODS NQ_MCBSP_LEGACY_ELEMENT=$NQ_MCBSP_LEGACY_ELEMENT NQ_MCBSP_LEGACY_THRESHOLD_FRAME=$NQ_MCBSP_LEGACY_THRESHOLD_FRAME NQ_MCBSP_LEGACY_PM_RUNTIME_HOLD=$NQ_MCBSP_LEGACY_PM_RUNTIME_HOLD NQ_MCBSP_NO_RX_ERR_IRQ=$NQ_MCBSP_NO_RX_ERR_IRQ NQ_MCBSP_LEGACY_TX_IRQ=$NQ_MCBSP_LEGACY_TX_IRQ NQ_MCBSP_NO_XRST_RESET=$NQ_MCBSP_NO_XRST_RESET NQ_MCBSP_FORCE_XRST_RESET_US=$NQ_MCBSP_FORCE_XRST_RESET_US NQ_MCBSP_STOP_ON_TX_UNDERFLOW=$NQ_MCBSP_STOP_ON_TX_UNDERFLOW NQ_MCBSP_TX_BURST=$NQ_MCBSP_TX_BURST NQ_MCBSP_BUFFER_SIZE_OVERRIDE=$NQ_MCBSP_BUFFER_SIZE_OVERRIDE NQ_MCBSP_TRIGGER_THRESHOLD=$NQ_MCBSP_TRIGGER_THRESHOLD NQ_MCBSP_PIO_TONE_MS=$NQ_MCBSP_PIO_TONE_MS NQ_MCBSP_PIO_TONE_FREQ=$NQ_MCBSP_PIO_TONE_FREQ NQ_MCBSP_PIO_TONE_AMP=$NQ_MCBSP_PIO_TONE_AMP NQ_MCBSP_PIO_THRESHOLD=$NQ_MCBSP_PIO_THRESHOLD NQ_MCBSP_PIO_TIMER_US=$NQ_MCBSP_PIO_TIMER_US NQ_MCBSP_PIO_FILL_WORDS=$NQ_MCBSP_PIO_FILL_WORDS NQ_MCBSP_PIO_IRQ=$NQ_MCBSP_PIO_IRQ NQ_MCBSP_PIO_XRDY_POLL=$NQ_MCBSP_PIO_XRDY_POLL NQ_MCBSP_PIO_DETACHED_STOP=$NQ_MCBSP_PIO_DETACHED_STOP NQ_MCBSP_FIFO_POLL_MS=$NQ_MCBSP_FIFO_POLL_MS NQ_MCBSP_FIFO_TRACE_SAMPLES=$NQ_MCBSP_FIFO_TRACE_SAMPLES NQ_MCBSP_DLB_TRACE_FRAMES=$NQ_MCBSP_DLB_TRACE_FRAMES NQ_MCBSP_DLB_BLOCK_FRAMES=$NQ_MCBSP_DLB_BLOCK_FRAMES NQ_MCBSP_DLB_DUMP_BLOCKS=$NQ_MCBSP_DLB_DUMP_BLOCKS NQ_MCBSP_RCR2_OVERRIDE=$NQ_MCBSP_RCR2_OVERRIDE NQ_MCBSP_XCR2_OVERRIDE=$NQ_MCBSP_XCR2_OVERRIDE NQ_MCBSP_SRGR1_OVERRIDE=$NQ_MCBSP_SRGR1_OVERRIDE NQ_MCBSP_SRGR2_OVERRIDE=$NQ_MCBSP_SRGR2_OVERRIDE NQ_MCBSP_PCR0_OVERRIDE=$NQ_MCBSP_PCR0_OVERRIDE NQ_MCBSP_XCCR_OVERRIDE=$NQ_MCBSP_XCCR_OVERRIDE NQ_MCBSP_DUMP_REGS=$NQ_MCBSP_DUMP_REGS NQ_TAS571X_DUMP_REGS=$NQ_TAS571X_DUMP_REGS NQ_TAS571X_LEGACY_STREAM_REINIT=$NQ_TAS571X_LEGACY_STREAM_REINIT NQ_TAS571X_LEGACY_POWER_DOWN=$NQ_TAS571X_LEGACY_POWER_DOWN NQ_TAS571X_MUTE_ON_TRIGGER=$NQ_TAS571X_MUTE_ON_TRIGGER NQ_TAS571X_IGNORE_MUTE=$NQ_TAS571X_IGNORE_MUTE NQ_TAS571X_SDI_OVERRIDE=$NQ_TAS571X_SDI_OVERRIDE NQ_TAS571X_SYS_CTRL1_OVERRIDE=$NQ_TAS571X_SYS_CTRL1_OVERRIDE NQ_TAS571X_SKIP_HW_PARAMS=$NQ_TAS571X_SKIP_HW_PARAMS NQ_TAS571X_CYCLE_MCLK_ON_LEGACY_RESET=$NQ_TAS571X_CYCLE_MCLK_ON_LEGACY_RESET NQ_TAS571X_ASYNC_LEGACY_STREAM_REINIT_MS=$NQ_TAS571X_ASYNC_LEGACY_STREAM_REINIT_MS NQ_TAS571X_ERR_POLL_MS=$NQ_TAS571X_ERR_POLL_MS NQ_TAS571X_FLAT_DSP=$NQ_TAS571X_FLAT_DSP NQ_STEELHEAD_AUDIO_DUMP=$NQ_STEELHEAD_AUDIO_DUMP NQ_AUDIO_FORMAT=$NQ_AUDIO_FORMAT NQ_AUDIO_INVERSION=$NQ_AUDIO_INVERSION NQ_LEGACY_S16_ONLY=$NQ_LEGACY_S16_ONLY NQ_STEELHEAD_CODEC_POWER_FIRST=$NQ_STEELHEAD_CODEC_POWER_FIRST NQ_STEELHEAD_CODEC_MCLK_STARTUP=$NQ_STEELHEAD_CODEC_MCLK_STARTUP NQ_STEELHEAD_MCBSP_CLK_STARTUP=$NQ_STEELHEAD_MCBSP_CLK_STARTUP NQ_STEELHEAD_MCBSP_CLK_HW_PARAMS=$NQ_STEELHEAD_MCBSP_CLK_HW_PARAMS NQ_STEELHEAD_SKIP_CODEC_FMT=$NQ_STEELHEAD_SKIP_CODEC_FMT NQ_STEELHEAD_LINK_FMT=$NQ_STEELHEAD_LINK_FMT NQ_STEELHEAD_LDC=$NQ_STEELHEAD_LDC NQ_BCLK_FS=$NQ_BCLK_FS NQ_RELOAD_DMA=$NQ_RELOAD_DMA NQ_DMA_LEGACY_CYCLIC_SYNC=$NQ_DMA_LEGACY_CYCLIC_SYNC NQ_DMA_LEGACY_CYCLIC_BURST=$NQ_DMA_LEGACY_CYCLIC_BURST NQ_DMA_LEGACY_CYCLIC_PACK=$NQ_DMA_LEGACY_CYCLIC_PACK NQ_DMA_LEGACY_CYCLIC_BLOCK_IRQ=$NQ_DMA_LEGACY_CYCLIC_BLOCK_IRQ NQ_DMA_DUMP_CYCLIC=$NQ_DMA_DUMP_CYCLIC NQ_DMA_DUMP_IRQ_LIMIT=$NQ_DMA_DUMP_IRQ_LIMIT NQ_DMA_CYCLIC_BURST_BITS=$NQ_DMA_CYCLIC_BURST_BITS NQ_DMA_FORCE_DESCRIPTOR_RESIDUE=$NQ_DMA_FORCE_DESCRIPTOR_RESIDUE NQ_DMA_AUDIO_TONE=$NQ_DMA_AUDIO_TONE NQ_DMA_AUDIO_TONE_RATE=$NQ_DMA_AUDIO_TONE_RATE NQ_DMA_AUDIO_TONE_FREQ=$NQ_DMA_AUDIO_TONE_FREQ NQ_DMA_AUDIO_TONE_AMP=$NQ_DMA_AUDIO_TONE_AMP NQ_DMA_AUDIO_TONE_CHANNEL=$NQ_DMA_AUDIO_TONE_CHANNEL NQ_DMA_AUDIO_TONE_DEV_ADDR=$NQ_DMA_AUDIO_TONE_DEV_ADDR NQ_DMA_AUDIO_TONE_NO_IRQ=$NQ_DMA_AUDIO_TONE_NO_IRQ NQ_DMA_AUDIO_TONE_FAKE_PERIOD=$NQ_DMA_AUDIO_TONE_FAKE_PERIOD NQ_DMA_FORCE_LCH_SIG=$NQ_DMA_FORCE_LCH_SIG NQ_DMA_FORCE_LCH=$NQ_DMA_FORCE_LCH NQ_DMA_FORCE_RW_PRIORITY=$NQ_DMA_FORCE_RW_PRIORITY sh -s" <<'REMOTE'
set -eu
killall aplay mpg123 speaker-test 2>/dev/null || true

set_module_param() {
	module="$1"
	param="$2"
	value="$3"
	path="/sys/module/$module/parameters/$param"
	if [ ! -e "$path" ]; then
		echo "missing module parameter $module:$param" >&2
		exit 1
	fi
	printf '%s\n' "$value" > "$path"
}

modprobe -r snd_soc_steelhead_tas5713 snd_soc_tas571x snd_soc_omap_mcbsp snd_soc_ti_sdma 2>/dev/null || true
if [ "$NQ_RELOAD_DMA" = "1" ]; then
	modprobe -r omap-dma 2>/dev/null || true
		modprobe omap-dma \
			nq_legacy_cyclic_sync="$NQ_DMA_LEGACY_CYCLIC_SYNC" \
			nq_legacy_cyclic_burst="$NQ_DMA_LEGACY_CYCLIC_BURST" \
			nq_legacy_cyclic_pack="$NQ_DMA_LEGACY_CYCLIC_PACK" \
			nq_legacy_cyclic_block_irq="$NQ_DMA_LEGACY_CYCLIC_BLOCK_IRQ" \
			nq_dump_cyclic="$NQ_DMA_DUMP_CYCLIC" \
			nq_dump_irq_limit="$NQ_DMA_DUMP_IRQ_LIMIT" \
			nq_cyclic_burst_bits="$NQ_DMA_CYCLIC_BURST_BITS" \
			nq_force_descriptor_residue="$NQ_DMA_FORCE_DESCRIPTOR_RESIDUE" \
			nq_audio_tone="$NQ_DMA_AUDIO_TONE" \
			nq_audio_tone_rate="$NQ_DMA_AUDIO_TONE_RATE" \
			nq_audio_tone_freq="$NQ_DMA_AUDIO_TONE_FREQ" \
			nq_audio_tone_amp="$NQ_DMA_AUDIO_TONE_AMP" \
			nq_audio_tone_channel="$NQ_DMA_AUDIO_TONE_CHANNEL" \
			nq_audio_tone_dev_addr="$NQ_DMA_AUDIO_TONE_DEV_ADDR" \
			nq_audio_tone_no_irq="$NQ_DMA_AUDIO_TONE_NO_IRQ" \
			nq_audio_tone_fake_period="$NQ_DMA_AUDIO_TONE_FAKE_PERIOD" \
			nq_force_lch_sig="$NQ_DMA_FORCE_LCH_SIG" \
			nq_force_lch="$NQ_DMA_FORCE_LCH" \
			nq_force_rw_priority="$NQ_DMA_FORCE_RW_PRIORITY"
		set_module_param omap_dma nq_legacy_cyclic_sync "$NQ_DMA_LEGACY_CYCLIC_SYNC"
		set_module_param omap_dma nq_legacy_cyclic_burst "$NQ_DMA_LEGACY_CYCLIC_BURST"
		set_module_param omap_dma nq_legacy_cyclic_pack "$NQ_DMA_LEGACY_CYCLIC_PACK"
		set_module_param omap_dma nq_legacy_cyclic_block_irq "$NQ_DMA_LEGACY_CYCLIC_BLOCK_IRQ"
		set_module_param omap_dma nq_dump_cyclic "$NQ_DMA_DUMP_CYCLIC"
		set_module_param omap_dma nq_dump_irq_limit "$NQ_DMA_DUMP_IRQ_LIMIT"
		set_module_param omap_dma nq_cyclic_burst_bits "$NQ_DMA_CYCLIC_BURST_BITS"
		set_module_param omap_dma nq_force_descriptor_residue "$NQ_DMA_FORCE_DESCRIPTOR_RESIDUE"
		set_module_param omap_dma nq_audio_tone "$NQ_DMA_AUDIO_TONE"
		set_module_param omap_dma nq_audio_tone_rate "$NQ_DMA_AUDIO_TONE_RATE"
		set_module_param omap_dma nq_audio_tone_freq "$NQ_DMA_AUDIO_TONE_FREQ"
		set_module_param omap_dma nq_audio_tone_amp "$NQ_DMA_AUDIO_TONE_AMP"
		set_module_param omap_dma nq_audio_tone_channel "$NQ_DMA_AUDIO_TONE_CHANNEL"
		set_module_param omap_dma nq_audio_tone_dev_addr "$NQ_DMA_AUDIO_TONE_DEV_ADDR"
		set_module_param omap_dma nq_audio_tone_no_irq "$NQ_DMA_AUDIO_TONE_NO_IRQ"
		set_module_param omap_dma nq_audio_tone_fake_period "$NQ_DMA_AUDIO_TONE_FAKE_PERIOD"
		set_module_param omap_dma nq_force_lch_sig "$NQ_DMA_FORCE_LCH_SIG"
		set_module_param omap_dma nq_force_lch "$NQ_DMA_FORCE_LCH"
		set_module_param omap_dma nq_force_rw_priority "$NQ_DMA_FORCE_RW_PRIORITY"
	fi
modprobe snd_soc_ti_sdma \
	nq_period_bytes="$NQ_SDMA_PERIOD_BYTES" \
	nq_periods="$NQ_SDMA_PERIODS"
modprobe snd_soc_omap_mcbsp \
	nq_legacy_element="$NQ_MCBSP_LEGACY_ELEMENT" \
	nq_legacy_threshold_frame="$NQ_MCBSP_LEGACY_THRESHOLD_FRAME" \
	nq_legacy_pm_runtime_hold="$NQ_MCBSP_LEGACY_PM_RUNTIME_HOLD" \
	nq_no_rx_err_irq="$NQ_MCBSP_NO_RX_ERR_IRQ" \
	nq_legacy_tx_irq="$NQ_MCBSP_LEGACY_TX_IRQ" \
	nq_no_xrst_reset="$NQ_MCBSP_NO_XRST_RESET" \
	nq_force_xrst_reset_us="$NQ_MCBSP_FORCE_XRST_RESET_US" \
	nq_stop_on_tx_underflow="$NQ_MCBSP_STOP_ON_TX_UNDERFLOW" \
	nq_tx_burst="$NQ_MCBSP_TX_BURST" \
	nq_buffer_size_override="$NQ_MCBSP_BUFFER_SIZE_OVERRIDE" \
	nq_trigger_threshold="$NQ_MCBSP_TRIGGER_THRESHOLD" \
	nq_pio_tone_ms="$NQ_MCBSP_PIO_TONE_MS" \
	nq_pio_tone_freq="$NQ_MCBSP_PIO_TONE_FREQ" \
	nq_pio_tone_amp="$NQ_MCBSP_PIO_TONE_AMP" \
	nq_pio_threshold="$NQ_MCBSP_PIO_THRESHOLD" \
	nq_pio_timer_us="$NQ_MCBSP_PIO_TIMER_US" \
	nq_pio_fill_words="$NQ_MCBSP_PIO_FILL_WORDS" \
	nq_pio_irq="$NQ_MCBSP_PIO_IRQ" \
	nq_pio_xrdy_poll="$NQ_MCBSP_PIO_XRDY_POLL" \
	nq_pio_detached_stop="$NQ_MCBSP_PIO_DETACHED_STOP" \
	nq_fifo_poll_ms="$NQ_MCBSP_FIFO_POLL_MS" \
	nq_fifo_trace_samples="$NQ_MCBSP_FIFO_TRACE_SAMPLES" \
	nq_dlb_trace_frames="$NQ_MCBSP_DLB_TRACE_FRAMES" \
	nq_dlb_block_frames="$NQ_MCBSP_DLB_BLOCK_FRAMES" \
	nq_dlb_dump_blocks="$NQ_MCBSP_DLB_DUMP_BLOCKS" \
	nq_rcr2_override="$NQ_MCBSP_RCR2_OVERRIDE" \
	nq_xcr2_override="$NQ_MCBSP_XCR2_OVERRIDE" \
	nq_srgr1_override="$NQ_MCBSP_SRGR1_OVERRIDE" \
	nq_srgr2_override="$NQ_MCBSP_SRGR2_OVERRIDE" \
	nq_pcr0_override="$NQ_MCBSP_PCR0_OVERRIDE" \
	nq_xccr_override="$NQ_MCBSP_XCCR_OVERRIDE" \
	nq_dump_regs="$NQ_MCBSP_DUMP_REGS"
modprobe snd_soc_tas571x \
	nq_dump_regs="$NQ_TAS571X_DUMP_REGS" \
	nq_legacy_stream_reinit="$NQ_TAS571X_LEGACY_STREAM_REINIT" \
	nq_legacy_power_down="$NQ_TAS571X_LEGACY_POWER_DOWN" \
	nq_mute_on_trigger="$NQ_TAS571X_MUTE_ON_TRIGGER" \
	nq_ignore_mute="$NQ_TAS571X_IGNORE_MUTE" \
	nq_sdi_override="$NQ_TAS571X_SDI_OVERRIDE" \
	nq_sys_ctrl1_override="$NQ_TAS571X_SYS_CTRL1_OVERRIDE" \
	nq_skip_hw_params="$NQ_TAS571X_SKIP_HW_PARAMS" \
	nq_cycle_mclk_on_legacy_reset="$NQ_TAS571X_CYCLE_MCLK_ON_LEGACY_RESET" \
	nq_async_legacy_stream_reinit_ms="$NQ_TAS571X_ASYNC_LEGACY_STREAM_REINIT_MS" \
	nq_err_poll_ms="$NQ_TAS571X_ERR_POLL_MS" \
	nq_flat_dsp="$NQ_TAS571X_FLAT_DSP"
modprobe snd_soc_steelhead_tas5713 \
	nq_audio_dump="$NQ_STEELHEAD_AUDIO_DUMP" \
	nq_audio_format="$NQ_AUDIO_FORMAT" \
	nq_audio_inversion="$NQ_AUDIO_INVERSION" \
	nq_legacy_s16_only="$NQ_LEGACY_S16_ONLY" \
	nq_codec_power_first="$NQ_STEELHEAD_CODEC_POWER_FIRST" \
	nq_codec_mclk_startup="$NQ_STEELHEAD_CODEC_MCLK_STARTUP" \
	nq_mcbsp_clk_startup="$NQ_STEELHEAD_MCBSP_CLK_STARTUP" \
	nq_mcbsp_clk_hw_params="$NQ_STEELHEAD_MCBSP_CLK_HW_PARAMS" \
	nq_skip_codec_fmt="$NQ_STEELHEAD_SKIP_CODEC_FMT" \
	nq_link_fmt="$NQ_STEELHEAD_LINK_FMT" \
	nq_ldc="$NQ_STEELHEAD_LDC" \
	nq_bclk_fs="$NQ_BCLK_FS"
lsmod | grep -E "^(omap_dma|snd_soc_(steelhead|tas571x|omap_mcbsp|ti_sdma))" || true
dmesg | tail -80 | grep -E "steelhead|tas571|mcbsp|sdma|omap-dma" || true
REMOTE
